/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "cpp-calculator.h"
#include <cassert>

int main() {
    // assert(UsingCalculator().compare("Using C++ calculator ...") == 0);
    assert(add(1,2) == 3);
    return 0;
}
